# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_images_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='genero',
            field=models.CharField(blank='true', choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
